CREATE TABLE VEICULO (
    placa CHAR(7) NOT NULL,
    cpf BIGINT(11) UNSIGNED NOT NULL,
    idModelo INT(6) UNSIGNED NOT NULL,
    idCategoria INT(2) UNSIGNED NOT NULL,
    chassi CHAR(17) NOT NULL,
    corPredominante VARCHAR(32) NOT NULL,
    anoFabricacao INT UNSIGNED NOT NULL,
    CONSTRAINT VEICULO_PK PRIMARY KEY (placa),
    CONSTRAINT VEICULO_PROPRIETARIO_FK FOREIGN KEY (cpf)
		REFERENCES PROPRIETARIO (cpf)
		ON DELETE RESTRICT
        ON UPDATE RESTRICT
) ENGINE=INNODB;

CREATE TABLE MODELO (
    idModelo INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
    descricao VARCHAR(32) NOT NULL,
    CONSTRAINT MODELO_PK PRIMARY KEY (idModelo),
    CONSTRAINT MODELO_UK UNIQUE (descricao)    
) ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE CATEGORIA (
    idCategoria INT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
    descricao VARCHAR(32) NOT NULL,
    CONSTRAINT CATEGORIA_PK PRIMARY KEY (idCategoria),
    CONSTRAINT CATEGORIA_UK UNIQUE (descricao)
) ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE PROPRIETARIO (
    cpf BIGINT(11) UNSIGNED NOT NULL,
    nome VARCHAR(80) NOT NULL,
    dataNascimento DATE NOT NULL,
    sexo ENUM('M','F') NOT NULL,
    uf CHAR(2) NOT NULL,
    cidade VARCHAR(80) NOT NULL,
    bairro VARCHAR(80) NOT NULL,
    lougradouro VARCHAR(80) NOT NULL,
    CONSTRAINT PROPRIETARIO_PK PRIMARY KEY (cpf)
) ENGINE=INNODB;

CREATE TABLE INFRACAO (
    idInfracao INT UNSIGNED NOT NULL AUTO_INCREMENT,
    placa CHAR(7) NOT NULL,
    matricula INT UNSIGNED NOT NULL,
    idTipoInfracao INT(1) UNSIGNED NOT NULL,
    dataHora DATETIME NOT NULL,
    latitude DECIMAL(10,8) NOT NULL,
    longitude DECIMAL(10,8) NOT NULL,
    CONSTRAINT INFRACAO_PK PRIMARY KEY (idInfracao),
    CONSTRAINT INFRACAO_UK UNIQUE (placa, dataHora, idTipoInfracao)
) ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE TIPOINFRACAO (
    idTipoInfracao INT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
    descricao VARCHAR(32) UNIQUE NOT NULL,
    valor DECIMAL(6,2) NOT NULL,
    CONSTRAINT TIPOINFRACAO_PK PRIMARY KEY (idTipoInfracao),
    CONSTRAINT TIPOINFRACAO_UK UNIQUE (descricao)
) ENGINE=INNODB AUTO_INCREMENT=1;

CREATE TABLE AGENTE (
    matricula INT UNSIGNED NOT NULL,
    nome VARCHAR(80) NOT NULL,
    dataContratacao DATE NOT NULL,
    CONSTRAINT AGENTE_PK PRIMARY KEY (matricula)
) ENGINE=INNODB;

CREATE TABLE telefone (
    cpf BIGINT(11) UNSIGNED NOT NULL NOT NULL,
    telefone INT UNSIGNED NOT NULL,
    CONSTRAINT telefone_UK UNIQUE (telefone, cpf)
) ENGINE=INNODB;